name: disptach_workflow

env:
  owner: nicolaspenagosm
  repo: actions
  
on:
  repository_dispatch:
    types: [my_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Test
        run: |
            echo "Executing the job..."
            # Here you can add the specific steps of your job

    
