name: Ping
env:
  REPO_OWNER: nicolaspenagosm
  REPO_NAME: actions
on:
  repository_dispatch:
    types: [run-ping]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
